version: 0.0
os: linux
#files:
#  - source: /index.html
#    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: scripts/update
      timeout: 300
      runas: ubuntu
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root
